---
version: "3.6"

x-besu-bootnode-def: &besu-bootnode-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |

      /opt/besu/bin/besu public-key export --to=/tmp/bootnode_pubkey;
      /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/nodekey \
        --min-gas-price=0 \
        --rpc-http-api=EEA,WEB3,ETH,NET,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PERM,IBFT ;

x-besu-def: &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |

      while [ ! -f "/opt/besu/public-keys/bootnode_pubkey" ]; do sleep 5; done ;
      /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/nodekey \
        --min-gas-price=0 \
        --rpc-http-api=EEA,WEB3,ETH,NET,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PERM,IBFT ;

services:
  validator1:
    <<: *besu-bootnode-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator1,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/tmp/
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
    networks:
      besu-testnet:
        ipv4_address: 172.16.239.11

  validator2:
    <<: *besu-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator2,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/:/config
      - ./config/nodes/validator2:/opt/besu/keys
    depends_on:
      - validator1
    networks:
      besu-testnet:
        ipv4_address: 172.16.239.12

  validator3:
    <<: *besu-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator3,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/:/config
      - ./config/nodes/validator3:/opt/besu/keys
    depends_on:
      - validator1
    networks:
      besu-testnet:
        ipv4_address: 172.16.239.13

  validator4:
    <<: *besu-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator4,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/:/config
      - ./config/nodes/validator4:/opt/besu/keys
    depends_on:
      - validator1
    networks:
      besu-testnet:
        ipv4_address: 172.16.239.14

  rpcnode:
    <<: *besu-def
    container_name: rpcnode
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=rpcnode,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/:/config
      - ./config/nodes/rpcnode:/opt/besu/keys
    depends_on:
      - validator1
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
    networks:
      besu-testnet:
        ipv4_address: 172.16.239.15

volumes:
  public-keys:
  member1tessera:
  member2tessera:
  member3tessera:

networks:
  besu-testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
